### ISSUE TITLE
/menu script hide issue

### ISSUE THREAD

**Issue by HaZePug** [XHawk87/CreateYourOwnMenus#11]
When I do /menu script hide if the menu script is long it will delete half of my script anyone help please

**Comment by XHawk87** [comment]
I would imagine that you're running into Minecraft's character limits. To hide the text, CYOM places a section symbol in front of each character so that it interprets it as a colour code and does not display it. This means it will effectively use twice as many characters while hidden and the text ends up getting truncated.

Perhaps a way around this would be to use CYOM to run a custom Skript command that does all of the things you want. It would keep your menu item's short, and you'd open up a lot more features for your menu item that Skript can provide. 

Here is the plugin page for Skript: https://dev.bukkit.org/projects/skript
Here is the official documentation: http://njol.ch/projects/skript/doc/
and this is a useful expansion for Skript that lets you do even more: https://skunity.com/
