### ISSUE TITLE
How To Get Players To Execute The Command

### ISSUE THREAD

**Issue by TacoCraft** [XHawk87/CreateYourOwnMenus#15]
How do i get the player who clicked it to execute the command, /sudo @p doesnt work.

**Comment by TacoCraft** [comment]
You could also add a player variable, a lot of people would like that

**Comment by XHawk87** [comment]
@TacoCraft /sudo @p will run the command as the player who activated that menu item, however they will require the permission to run that command, if it has a permission.

I am not sure what you're asking for with a 'player variable'. The player selector is @p, and will be substituted in the command with the name of the player that activated the menu item. 

If you want to be able to use the full range of Minecraft command selectors and NBT data tags, you can run a function as that player. E.g. /execute @p ~ ~ ~ function MyNamespace:Path/To/My/Function

See [Function on the Minecraft wiki](https://minecraft.gamepedia.com/Function) for help.

**Comment by TacoCraft** [comment]
'/sudo @p menu open test' does not work. Neither does '/execute @p ~ ~ ~ menu open test'. On addition to that, functions are only in 1.12+ and my server is currently running 1.8

**Comment by XHawk87** [comment]
There are a couple of tests you can do:
`/say @p`
This test will display the name of the player who activated the menu item. This proves that it is using the correct player name.

The other is for the clicking player to type the command themselves. In this case:
`/menu open test`
Instead of running it in a menu item. This proves that they have the permission to use it.

Also, where possible, you should use the player-targetted syntax for a command before trying to use sudo. This sidesteps the problem of that player needing permissions. In this case of /menu open, this would be:
`/menu open @p test`
