### ISSUE TITLE
HELP! Please!

### ISSUE THREAD

**Issue by RealAndrewPlayz** [XHawk87/CreateYourOwnMenus#17]
Whenever i give someone the menu box it also opens on my screen when they open it, This is the lore
/menu script RealAndrewPlayz lore /menu open @p m

**Comment by XHawk87** [comment]
Hi RealAndrewPlayz

That is some very confusing scripting you have done there. 

If that is how the lore on the item really reads, it would fail because the sub-command is `append` or `add` not `lore`. Even if you corrected that, it would mean that every time someone uses that menu item, it would add the lore `/menu open @p m` to whatever item that YOU (not the person using the menu item) happen to be holding at the time.

If you want an item that opens a menu for the player clicking it, the lore should actually read `/menu open @p MY_MENU_ID_HERE`.

The command to add lore to an item you are holding is `/menu script add /MY_COMMAND_HERE`

**Comment by RealAndrewPlayz** [comment]
oops i meant
/menu script RealAndrewPlayz append /menu open m
My bad! xD

**Comment by RealAndrewPlayz** [comment]
"/menu open @p MY_MENU_ID_HERE" Im confused as in i put /menu open @p then the menu is because the menu id is "m"

**Comment by XHawk87** [comment]
If the menu ID is 'm', then the lore should read `/menu open @p m`

This should open the menu named 'm' for the player that activated that menu item.

**Comment by RealAndrewPlayz** [comment]
"If the menu ID is 'm', then the lore should read /menu open @p m

This should open the menu named 'm' for the player that activated that menu item."
That is what it reads but... when they open it, it also opens on my screen every time!?!?!

**Comment by XHawk87** [comment]
It may be holding onto hidden data from an earlier attempt that opens it for you as well. Try destroying that item and starting over with a fresh one.
