### ISSUE TITLE
/sudo doesn't force player to execute command

### ISSUE THREAD

**Issue by DracoDragon93** [XHawk87/CreateYourOwnMenus#26]
On Version 0.6.0, CYOM's version of /sudo doesn't make the player run any commands. If you were to do "/sudo @p test", instead of the player executing the command "test", it forces the player to send a chat message saying "@p test". This is only with CYOM because doing /essentials:sudo @p test does what is expected making the player execute the command like normal. My server is running Spigot 1.13.2

**Comment by XHawk87** [comment]
Thanks for the report. I will have a fix in the next test build

**Comment by XHawk87** [comment]
It looks like this is caused by two issues, when this was rewritten in code style improvements, I neglected to add the forward slash and cut off the first parameter. Easily fixed. 

The second issue is that you appear to have run the command outside of a menu item, and that means the @p did not work. This isn't a vanilla "Brigadier" command, so target selectors don't work, and the cut-down selectors for CYOM only work inside menu scripts. To address this, and resolve the conflict with essentials sudo, I have decided to make CYOM sudo and special menu command. It will now only work in menus. 

Would you be willing to test the changes for me when I release the next test build?

**Comment by XHawk87** [comment]
https://github.com/XHawk87/CreateYourOwnMenus/releases/tag/0.6.2

**Comment by DracoDragon93** [comment]
The custom menus with sudo commands work now, but sudo commands ran outside of menus are still not working. "/sudo @p say test" or "/sudo Draco say test" for example ran either by a command block, player. or console always returns with "/sudo [player] [command]" and "/sudo <player> <command [args]>" regardless of what the command or arguments are.

**Comment by XHawk87** [comment]
See above
> I have decided to make CYOM sudo a special menu command. It will now only work in menus.

**Comment by XHawk87** [comment]
I've removed the references to the sudo command from the plugin.yml so it should no longer conflict with essentials sudo

https://github.com/XHawk87/CreateYourOwnMenus/releases/tag/0.6.3
