### ISSUE TITLE
Cant put items into menu

### ISSUE THREAD

**Issue by minda54323** [XHawk87/CreateYourOwnMenus#27]
Hey guys
I have a little problem in my menus. I cant edit first 4 slots in any menu. Its really bad, I cant setup menus. Please someone help me. Sorry for my Eng lol

**Comment by XHawk87** [comment]
I need a little more information about this in order to figure out what's wrong. Can you please tell me: 

- What version of Minecraft are you playing in? Modded?
- What is your server software and version?
- Can you show me a screenshot or GIF showing the issue?
- Do you get any error messages in chat or in the server log? When it happens? At startup? 
- What steps are needed to reproduce the problem?

**Comment by minda54323** [comment]
Ok...
1.8.9 no moded
Software bungee cord...but this version is paperspigot..if you mean that
its not showing anything...just...when i put something there..it remove instantly
no nothing
idk

**Comment by minda54323** [comment]
sorry if you mean something other then i wrote..this is my first server and im not a programmer or something...just fun lol

**Comment by XHawk87** [comment]
If you're running 1.8.9, which version of CYOM are you using? The latest ones are not backwards-compatible to that version.

**Comment by minda54323** [comment]
no it is running well...just this...
version is 0.5.9

**Comment by XHawk87** [comment]
That's the correct version to use. Are you running any other plugins that could be interfering with it?

**Comment by minda54323** [comment]
No...

**Comment by XHawk87** [comment]
I am running out of ideas. You could try changing the version of spigot up or down to see if it is a bug or compatibility issue with that version of paperspigot

**Comment by minda54323** [comment]
I try to reinstall my whole plugin or download another... But thank you for your time :3
