### ISSUE TITLE
Commands with { }

### ISSUE THREAD

**Issue by matejmichalek2004** [XHawk87/CreateYourOwnMenus#35]
How can I add script (command) with { } to an item?
For example /tellraw @a {"text":"Someone joined the game"}

_/menu script add /tellraw @a {"text":"Someone joined the game"}_

After right clicking the item i need to input "text":"Someone joined the game" in chat.
Can I somehow add command with these brackets?

**Comment by XHawk87** [comment]
Unfortunately, you can't use JSON with curly braces in commands inside of a menu item directly. This is because we already used curly braces for dynamic arguments before this syntax was used in minecraft, and we can't change that without breaking the existing functionality for other users.

However, you can work around this, and I would recommend this in general, by using a command scripting plugin such as Skript or VariableTriggers etc. There are many options available in spigot/dbo. Create a command/trigger/script in this other plugin and then run it from a menu item. This will give your menu items a great deal more power and functionality.
