### ISSUE TITLE
Putting Items in menu

### ISSUE THREAD

**Issue by zaid4500** [XHawk87/CreateYourOwnMenus#6]
Im having trouble putting items in a open menu. I have the items execute commands, but I can't seem to get the items to go inside the open menu

**Comment by XHawk87** [comment]
In order to add an item to a menu, the menu must be open for editing and not for using. The command for this is `/menu edit [id]` where [id] is replaced by the ID for that menu.

You move the desired item into the inventory that opens up, just as if it were any other inventory. When you close the inventory (as you would any other inventory) it saves the menu and you can then open it for using with the command `/menu open [id]`

You can find a full list of commands and permissions here: http://dev.bukkit.org/bukkit-plugins/createyourownmenus/pages/commands-and-permissions/

There is also a video tutorial here: https://www.youtube.com/watch?v=T9shRV383qg&feature=youtu.be

Written tutorials are in the forum: http://dev.bukkit.org/bukkit-plugins/createyourownmenus/forum/

If you still have issues, please describe exactly what you did and what went wrong, and I can look into it.

**Comment by zaid4500** [comment]
oh thank you, you responded very quickly
